# Generated by Django 4.2.11 on 2025-06-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_salesprediction', 'Can view sales prediction'), ('view_clientsegmentation', 'Can view client segmentation')],
                'managed': False,
            },
        ),
    ]
